Repository uwreact/uwreact_robot, pull requests merged in 2019-03, with the labels that each got.

#66 Ignore .pyc files
  .gitignore
Labels: 🚀 feature

#64 Add clang-format
  .clang-format
  .github/PULL_REQUEST_TEMPLATE.md
  .travis.yml
  README.md
Labels: 🚀 feature

#67 Remove dependency hack
  .travis.yml
Labels: :bug: bug

#65 Added network visualizer Catkin package
  network_visualizer/CMakeLists.txt
  network_visualizer/package.xml
  network_visualizer/scripts/open_network_visualizer
  network_visualizer/setup.py
  network_visualizer/src/network_visualizer/__init__.py
  network_visualizer/src/network_visualizer/window.py
Labels: ❗urgent, 🧠 planning

#70 Add .clang-tidy config
  .clang-tidy
  run_clang_tidy.py
Labels: 🚀 feature

#71 Prefer else on same line as closing brace
  .clang-format
Labels: 🚀 feature

#72 Add yapf and pylint configs
  .pylintrc
  .style.yapf
  README.md
  run_clang_tidy.py
  uwreact_planning/network_visualizer/scripts/open_network_visualizer
  uwreact_planning/network_visualizer/setup.py
  uwreact_planning/network_visualizer/src/network_visualizer/window.py
Labels: 🚀 feature

#74 Update maintainer email to maintainers@uwreact.ca
  .travis.yml
  uwreact_bringup/package.xml
  uwreact_controls/uwreact_controls/package.xml
  uwreact_description/package.xml
  uwreact_perception/uwreact_perception/package.xml
  uwreact_planning/network_visualizer/package.xml
  uwreact_planning/uwreact_planning/package.xml
  uwreact_robot/package.xml
Labels: 📖 documentation

#73 Zed depth image to laser scan
  uwreact_bringup/launch/.gitkeep
  uwreact_bringup/launch/perception.launch
  uwreact_bringup/launch/zeds.launch
  uwreact_bringup/package.xml
Labels: 🚀 feature

#79 CI style checks
  .clang-tidy
  .pylintrc
  .travis.yml
  run_clang_tidy.py
  run_linters.py
  uwreact_planning/network_visualizer/package.xml
  uwreact_planning/network_visualizer/scripts/open_network_visualizer
  uwreact_planning/network_visualizer/src/network_visualizer/window.py
Labels: 🚀 feature
